# Generated by Django 6.0 on 2025-12-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='门店名称')),
                ('address', models.CharField(max_length=255, verbose_name='门店地址')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
            },
        ),
        migrations.CreateModel(
            name='MahjongTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, verbose_name='桌号')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='booking.store', verbose_name='所属门店')),
            ],
            options={
                'verbose_name': '麻将桌',
                'verbose_name_plural': '麻将桌',
                'unique_together': {('store', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='预计开始时间')),
                ('num_games', models.PositiveIntegerField(default=4, verbose_name='预计局数 (半庄)')),
                ('estimated_end_time', models.DateTimeField(editable=False, verbose_name='预计结束时间')),
                ('status', models.CharField(choices=[('PENDING', '匹配中'), ('CONFIRMED', '匹配成功'), ('CANCELED', '已取消'), ('EXPIRED', '已过期'), ('COMPLETED', '已完成')], default='PENDING', max_length=20, verbose_name='预约状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bookings', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('participants', models.ManyToManyField(related_name='joined_bookings', to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.mahjongtable', verbose_name='安排牌桌')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.store', verbose_name='预约门店')),
            ],
            options={
                'verbose_name': '对局预约',
                'verbose_name_plural': '对局预约',
                'ordering': ['start_time'],
            },
        ),
    ]
