# Generated by Django 6.0 on 2025-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahjongtable',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='别名/位置描述'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('STANDARD', '标准预约')], default='STANDARD', max_length=10, verbose_name='预约类型'),
        ),
    ]
