# Generated by Django 6.0 on 2025-12-20 19:08

from django.db import migrations, models


def merge_statuses(apps, schema_editor):
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.filter(status='EXPIRED').update(status='CANCELED')
    Booking.objects.filter(status='COMPLETED').update(status='CONFIRMED')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_mahjongtable_alias_alter_booking_booking_type'),
    ]

    operations = [
        migrations.RunPython(merge_statuses, noop),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', '匹配中'), ('CONFIRMED', '匹配成功'), ('CANCELED', '已取消')], default='PENDING', max_length=10, verbose_name='预约状态'),
        ),
    ]
